[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  madhephaestus/ESP32Servo
build_flags =
  -D WIFI_ENABLED=1
  '-D WIFI_SSID="M35 de Camila"'
  '-D WIFI_PASSWORD="12345678"'
  '-D FIREBASE_DATABASE_URL="https://projeto-top-redes-default-rtdb.firebaseio.com"'
  '-D LOCKER_ID="locker-a-12"'
