[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D WIFI_ENABLED=1
  -D WIFI_SSID=\"Locallink-33145\"
  -D WIFI_PASSWORD=\"75229388\"
  -D FIREBASE_DATABASE_URL=\"https://projeto-top-redes-default-rtdb.firebaseio.com\"
  -D LOCKER_ID=\"locker-a-12\"
